name: CI/CD Audit Service

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - "services/audit-service/**"

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    # Si quieres usar Environment Secrets, descomenta esta línea:
    # environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'qa' }}
    
    # Si usas Environment Secrets, los secrets se cargarán automáticamente
    # Si usas Repository Secrets, no necesitas la línea environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Si usas Repository Secrets:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          
          # Si usas Environment Secrets:
          # username: ${{ vars.DOCKER_USER }}
          # password: ${{ vars.DOCKER_PASS }}

      - name: Build Docker image
        working-directory: services/audit-service
        run: |
          docker build \
            --tag ${{ secrets.DOCKER_USER }}/audit-service:${{ github.sha }} \
            --tag ${{ secrets.DOCKER_USER }}/audit-service:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/audit-service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/audit-service:latest