name: CI/CD Lab Service

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - "services/lab-service/**"

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'qa' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: services/lab-service
        run: npm install

      - name: Build Docker image
        working-directory: services/lab-service
        run: docker build -t ${{ secrets.DOCKER_USER }}/lab-service:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/lab-service:latest
